<?php
/**
 * Created by PhpStorm.
 * User: chengang
 * Date: 2019-03-29
 * Time: 11:29
 */

namespace chengang\joyInteraction;


use yii\base\Model;

//请求头部对象
class HttpHeader extends Model
{
    public $source; //源
    public $timestamp; //调用时间
    public $sign; //签名字符串

    public function rules()
    {
        return [
            [['source', 'timestamp', 'sign'], 'required'],
            [['source', 'sign'], 'string'],
            [['timestamp'], 'integer'],
        ];
    }

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->timestamp = time();
    }

}