<?php
/**
 * Created by PhpStorm.
 * User: chengang
 * Date: 2019-03-29
 * Time: 11:29
 */

namespace chengang\joyInteraction;


use yii\base\Model;
use yii\helpers\ArrayHelper;
use yii\web\UnauthorizedHttpException;

//请求头部对象
class HttpHeader extends Model
{
    public $source; //源
    public $timestamp; //调用时间
    public $sign; //签名字符串
    public $ip; //请求ip

    public function rules()
    {
        return [
            [['source', 'timestamp', 'sign'], 'required'],
            [['source', 'sign'], 'string'],
            [['timestamp'], 'integer'],
            ['timestamp', function ($attribute, $params) {
                $outtime = ArrayHelper::getValue(\Yii::$app->params, 'httpValidate.outtime');
                $outtime = $outtime ? $outtime : 3;
                if ((time() - $this->timestamp) / 60 > $outtime) {
                    $this->addError($attribute, '请求超时');
                }
            }, 'on' => ['validate']
            ], //验证场景时验证
            //请求来源验证
            ['source', function ($attribute) {
                $sources = ArrayHelper::getValue(\Yii::$app->params, 'httpValidate.sources');
                if (!in_array($this->source, $sources)) {
                    throw new UnauthorizedHttpException('source 有误');
                }

            }, 'on' => ['validate']],
            //ip验证
            ['ip', function ($attribute) {
                $ips = ArrayHelper::getValue(\Yii::$app->params, 'httpValidate.ips');
                if (!in_array($this->ip, $ips)) {
                    throw new UnauthorizedHttpException('ip禁止访问');
                }

            }, 'on' => ['validate']],

        ];
    }

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->timestamp = time();
    }

}